// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVBqKF4sIzFr_Y_GjXSMhzKChQiZoGn7k',
    appId: '1:456288015168:web:7ee78db9a2700dd517a0a5',
    messagingSenderId: '456288015168',
    projectId: 'labour-connect-3f779',
    authDomain: 'labour-connect-3f779.firebaseapp.com',
    storageBucket: 'labour-connect-3f779.firebasestorage.app',
    measurementId: 'G-677KJTTMGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9OTOAdlpQ5_517-J-QB7oxpjtqaiNqYM',
    appId: '1:456288015168:android:e09f09f9df0bcf5817a0a5',
    messagingSenderId: '456288015168',
    projectId: 'labour-connect-3f779',
    storageBucket: 'labour-connect-3f779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwpN4GAuN-UXRqnnqcxK4NJ8HauO7Bh8',
    appId: '1:456288015168:ios:9609e16c6cd5511417a0a5',
    messagingSenderId: '456288015168',
    projectId: 'labour-connect-3f779',
    storageBucket: 'labour-connect-3f779.firebasestorage.app',
    iosBundleId: 'com.example.labourConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXwpN4GAuN-UXRqnnqcxK4NJ8HauO7Bh8',
    appId: '1:456288015168:ios:9609e16c6cd5511417a0a5',
    messagingSenderId: '456288015168',
    projectId: 'labour-connect-3f779',
    storageBucket: 'labour-connect-3f779.firebasestorage.app',
    iosBundleId: 'com.example.labourConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVBqKF4sIzFr_Y_GjXSMhzKChQiZoGn7k',
    appId: '1:456288015168:web:c7a86694ece25c5817a0a5',
    messagingSenderId: '456288015168',
    projectId: 'labour-connect-3f779',
    authDomain: 'labour-connect-3f779.firebaseapp.com',
    storageBucket: 'labour-connect-3f779.firebasestorage.app',
    measurementId: 'G-65PJGP182N',
  );
}
